/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duelgame;

import java.util.HashSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mikami
 */
public class GameUI extends javax.swing.JFrame {

    /**
     * Creates new form GameUI
     */
    public GameUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        changesPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botHealthChangesLabel = new javax.swing.JLabel();
        playerHealthChangesLabel = new javax.swing.JLabel();
        playerManaChangesLabel = new javax.swing.JLabel();
        botManaChangesLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        slashButton = new javax.swing.JButton();
        shieldButton = new javax.swing.JButton();
        channelButton = new javax.swing.JButton();
        blastButton = new javax.swing.JButton();
        lockButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        humanHealthText = new javax.swing.JTextField();
        humanActionText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        humanManaText = new javax.swing.JTextField();
        humanShieldText = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        botHealthText = new javax.swing.JTextField();
        botActionText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        botManaText = new javax.swing.JTextField();
        botShieldText = new javax.swing.JTextField();

        changesPanel.setLayout(new java.awt.GridBagLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Player");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        changesPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bot");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        changesPanel.add(jLabel4, gridBagConstraints);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("damage taken");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        changesPanel.add(jLabel7, gridBagConstraints);

        botHealthChangesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botHealthChangesLabel.setText("jLabel3");
        botHealthChangesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        changesPanel.add(botHealthChangesLabel, gridBagConstraints);

        playerHealthChangesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerHealthChangesLabel.setText("jLabel3");
        playerHealthChangesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        changesPanel.add(playerHealthChangesLabel, gridBagConstraints);

        playerManaChangesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerManaChangesLabel.setText("jLabel3");
        playerManaChangesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        changesPanel.add(playerManaChangesLabel, gridBagConstraints);

        botManaChangesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botManaChangesLabel.setText("jLabel3");
        botManaChangesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        changesPanel.add(botManaChangesLabel, gridBagConstraints);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("mana changes");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        changesPanel.add(jLabel12, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DUEL GAME");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("mainGameFrame"); // NOI18N

        slashButton.setText("SLASH");
        slashButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        slashButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slashButton.setMultiClickThreshhold(2L);
        slashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slashButtonActionPerformed(evt);
            }
        });

        shieldButton.setText("SHIELD");
        shieldButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        shieldButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shieldButton.setMultiClickThreshhold(2L);
        shieldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shieldButtonActionPerformed(evt);
            }
        });

        channelButton.setText("CHANNEL");
        channelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        channelButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        channelButton.setMultiClickThreshhold(2L);
        channelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channelButtonActionPerformed(evt);
            }
        });

        blastButton.setText("BLAST");
        blastButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        blastButton.setDefaultCapable(false);
        blastButton.setEnabled(false);
        blastButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        blastButton.setMultiClickThreshhold(2L);
        blastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blastButtonActionPerformed(evt);
            }
        });

        lockButton.setText("LOCK CHOICE AND CONTINUE");
        lockButton.setMultiClickThreshhold(2L);
        lockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(slashButton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shieldButton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(channelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blastButton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lockButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slashButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shieldButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(channelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blastButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel2.setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Health");
        jPanel2.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Action");
        jPanel2.add(jLabel2);

        humanHealthText.setEditable(false);
        humanHealthText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        humanHealthText.setText("5");
        humanHealthText.setFocusable(false);
        jPanel2.add(humanHealthText);

        humanActionText.setEditable(false);
        humanActionText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        humanActionText.setText("------------");
        humanActionText.setToolTipText("");
        humanActionText.setFocusable(false);
        humanActionText.setMaximumSize(new java.awt.Dimension(69, 22));
        humanActionText.setMinimumSize(new java.awt.Dimension(69, 22));
        humanActionText.setPreferredSize(new java.awt.Dimension(69, 22));
        jPanel2.add(humanActionText);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Mana");
        jPanel2.add(jLabel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Shield");
        jPanel2.add(jLabel6);

        humanManaText.setEditable(false);
        humanManaText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        humanManaText.setText("0");
        humanManaText.setFocusable(false);
        jPanel2.add(humanManaText);

        humanShieldText.setEditable(false);
        humanShieldText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        humanShieldText.setText("0");
        humanShieldText.setFocusable(false);
        jPanel2.add(humanShieldText);

        jPanel3.setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Health");
        jPanel3.add(jLabel8);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Action");
        jPanel3.add(jLabel9);

        botHealthText.setEditable(false);
        botHealthText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botHealthText.setText("5");
        botHealthText.setFocusable(false);
        jPanel3.add(botHealthText);

        botActionText.setEditable(false);
        botActionText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botActionText.setText("------------");
        botActionText.setFocusable(false);
        botActionText.setMaximumSize(new java.awt.Dimension(69, 22));
        botActionText.setMinimumSize(new java.awt.Dimension(69, 22));
        botActionText.setPreferredSize(new java.awt.Dimension(69, 22));
        jPanel3.add(botActionText);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Mana");
        jPanel3.add(jLabel10);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Shield");
        jPanel3.add(jLabel11);

        botManaText.setEditable(false);
        botManaText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botManaText.setText("0");
        botManaText.setFocusable(false);
        botManaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botManaTextActionPerformed(evt);
            }
        });
        jPanel3.add(botManaText);

        botShieldText.setEditable(false);
        botShieldText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botShieldText.setText("0");
        botShieldText.setFocusable(false);
        jPanel3.add(botShieldText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showChanges() {
        int[] humanChanges = game.getPlayerChanges(0);
        int[] botChanges = game.getPlayerChanges(1);
        playerHealthChangesLabel.setText("" + humanChanges[0]);
        playerManaChangesLabel.setText("" + humanChanges[1]);
        botHealthChangesLabel.setText("" + botChanges[0]);
        botManaChangesLabel.setText("" + botChanges[1]);
        JOptionPane.showMessageDialog(null,changesPanel,"Result of actions",
                                        JOptionPane.PLAIN_MESSAGE);
      /*
        JOptionPane.showMessageDialog(new JFrame(),
                message,
                "Result of actions",
                JOptionPane.PLAIN_MESSAGE);
*/
    }
    public void showProperties() {
        int[] botProperties = game.getPlayerProperties(1);
        int[] humanProperties = game.getPlayerProperties(0);
        humanHealthText.setText("" + humanProperties[0]);
        humanManaText.setText("" + humanProperties[1]);
        humanShieldText.setText("" + humanProperties[2]);
        botHealthText.setText("" + botProperties[0]);
        botManaText.setText("" + botProperties[1]);
        botShieldText.setText("" + botProperties[2]);
    }

    public void updateButtons() {
        shieldButton.setEnabled(game.shieldEnabled());
        blastButton.setEnabled(game.blastEnabled());
        channelButton.setEnabled(game.channelEnabled());
    }

    public void updateChoice(int actionIdx) {
        game.setHumanAction(actionIdx);
        humanActionText.setText(ACTION_NAME[game.getActionIdx(0)]);
        showProperties();
    }

    private static final String[] ACTION_NAME = {"SLASH", "SHIELD", "CHANNEL", "BLAST", "IDLE"};
    private void slashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slashButtonActionPerformed
        updateChoice(0);
    }//GEN-LAST:event_slashButtonActionPerformed

    private void shieldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shieldButtonActionPerformed
        updateChoice(1);
    }//GEN-LAST:event_shieldButtonActionPerformed

    private void channelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channelButtonActionPerformed
        updateChoice(2);
    }//GEN-LAST:event_channelButtonActionPerformed

    private void blastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blastButtonActionPerformed
        updateChoice(3);
    }//GEN-LAST:event_blastButtonActionPerformed

    private void lockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockButtonActionPerformed
        if (game.isPlayerReady()) {
            game.runGameLogic();
            //This is put here because the bot choice should
            //only be shown after player has chosen
            botActionText.setText(ACTION_NAME[game.getActionIdx(1)]);
            showChanges();
            showProperties();
            updateButtons();
            checkGameCondition();
            // TODO: Centering frames
            // popup frame showChangesFrame
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Choose an action", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lockButtonActionPerformed

    private void botManaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botManaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botManaTextActionPerformed

    private void checkGameCondition() {
        if (game.isFinished()) {
            JOptionPane.showMessageDialog(new JFrame(), game.getWinner() + "\n A new game will start now", "Dialog",
                    JOptionPane.INFORMATION_MESSAGE);            
            game = new DuelGame();
        }
        showProperties();
        updateButtons();
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameUI().setVisible(true);
            }
        });
        game = new DuelGame();
    }
    private static DuelGame game;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blastButton;
    private javax.swing.JTextField botActionText;
    private javax.swing.JLabel botHealthChangesLabel;
    private javax.swing.JTextField botHealthText;
    private javax.swing.JLabel botManaChangesLabel;
    private javax.swing.JTextField botManaText;
    private javax.swing.JTextField botShieldText;
    private javax.swing.JPanel changesPanel;
    private javax.swing.JButton channelButton;
    private javax.swing.JTextField humanActionText;
    private javax.swing.JTextField humanHealthText;
    private javax.swing.JTextField humanManaText;
    private javax.swing.JTextField humanShieldText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton lockButton;
    private javax.swing.JLabel playerHealthChangesLabel;
    private javax.swing.JLabel playerManaChangesLabel;
    private javax.swing.JButton shieldButton;
    private javax.swing.JButton slashButton;
    // End of variables declaration//GEN-END:variables

}
